Linking database
UnitTestBot/Bear pull request #2
Opened 2023-03-24 11:21 UTC by MashaK5

2023-03-31 14:45 UTC, ladisgin requested changes

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Citnames.cc
> +                    auto result_compile = output_compile.from_json(arguments_.output_compile, entries_compile)
delete copy-paste

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Citnames.cc
> +                    rust::Ok(std::pair<size_t, size_t>(result_compile.unwrap(), result_link.unwrap()))
change pair to sum

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Output.cc
> +            const auto check = [this](const fs::path &file) -> bool {
move to static function

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Output.cc
> +                const auto &file = entry.file.value();
don't create variable

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Output.cc
> +                return std::all_of(files.begin(), files.end(), [&](const auto &file){
don't use second lambda

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Output.cc
> +            __builtin_unreachable();
change to return false

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Output.cc
> +    size_t hash_file_or_files(const cs::Entry &entry) {
delete duplicate checker if export link commands enable

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Output.h
> +        std::optional<std::list<fs::path>> files;
delete optional

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Output.cc
> +        if (not entry.file.has_value() && not entry.files.has_value()) {
add validate function file.empty() && files.empty()

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/Output.cc
> +        const auto contains_file = j.contains("file");
delete this after delete optional

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/semantic/Parsers.cc
> +        for (const auto &[candidate, info] : flags_) {
report to original bear

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/semantic/Parsers.cc
> +                    candidate_best = std::optional<std::string>(std::string(candidate));
change to make optional

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/semantic/Parsers.cc
> +        size_t prefix_length_best = 0;
use length of candidate_best

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/semantic/Parsers.cc
> +            ? check_partial(key, *(flags_.find(candidate_best.value())))
change and rename check_partial

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/semantic/Semantic.cc
> +                    : std::optional(static_cast<fs::path>(abspath(source, working_dir).string() + ".o")),
use operator+= from fs::path

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/semantic/Semantic.cc
> +        std::list<cs::Entry> results;
merge in one string

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/semantic/ToolGcc.cc
>          if (is_compiler_call(execution.executable)) {
run is_compiler_call only for compile and add is_linker_call

2023-03-31 14:45 UTC, ladisgin commented on source/citnames/source/semantic/ToolGcc.cc
> +                    if (has_linker(flags)) {
delete copy-paste

2023-04-03 12:42 UTC, MashaK5 commented on source/citnames/source/Output.cc
> +                return std::all_of(files.begin(), files.end(), [&](const auto &file){
Из-за использования полей не получается сделать check static (только inline), из-за этого не получается вызвать без второй лямбды.

2023-04-07 14:09 UTC, ladisgin requested changes

2023-04-07 14:09 UTC, ladisgin commented on source/citnames/source/Citnames.cc
> +//        configuration.output.content.without_existence_check = true;
delete unused comment

2023-04-07 14:09 UTC, ladisgin commented on source/citnames/source/Citnames.cc
> +            .map<cs::Configuration>([&args](auto config) {
why not add `customize_configuration` into `into_configuration` instead of use map?

2023-04-07 14:09 UTC, ladisgin commented on source/citnames/source/Output.cc
> +#include <optional>
do you still need to include `optional` here?

2023-04-07 14:09 UTC, ladisgin commented on source/citnames/source/Output.cc
> +            return exists(file) && to_include(file) && !to_exclude(file);
rewrite as `return (config.without_existence_check || exists(file)) && to_include(file) && !to_exclude(file);`

2023-04-07 14:09 UTC, ladisgin commented on source/citnames/source/Output.cc
> +            entry.files.begin(),
remove files from hash

2023-04-07 15:37 UTC, ladisgin approved these changes

2023-04-07 15:38 UTC, merged